name: Build & Auto Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    name: Build & Release on main
    runs-on: windows-latest
    permissions:
      contents: write  # needed to create release/tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore Enfolderer.sln
      - name: Build Release
        run: dotnet build Enfolderer.sln -c Release --no-restore
      - name: Publish Self-contained Single File (win-x64)
        run: >-
          dotnet publish Enfolderer.App -c Release -r win-x64 --self-contained true
          -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
          -o publish/win-x64
      - name: Publish Framework-dependent Single File (win-x64)
        run: >-
          dotnet publish Enfolderer.App -c Release -r win-x64 --self-contained false
          -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
          -o publish/win-x64-fd
      - name: Create Zip Packages
        shell: pwsh
        run: |
          Compress-Archive -Path publish/win-x64/* -DestinationPath Enfolderer-win-x64-selfcontained.zip
          Compress-Archive -Path publish/win-x64-fd/* -DestinationPath Enfolderer-win-x64-frameworkdependent.zip
      - name: Compute Tag
        id: tag
        shell: pwsh
        run: |
          $ts = (Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss')
          $short = '${{ github.sha }}'.Substring(0,7)
          $tag = "vauto-$ts-$short"
          echo "tag=$tag" >> $env:GITHUB_OUTPUT
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body: "Automated release for commit ${{ github.sha }}"
          artifacts: |
            Enfolderer-win-x64-selfcontained.zip
            Enfolderer-win-x64-frameworkdependent.zip
            sample_collection.csv
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
